### ISSUE TITLE
Mattermost 3.3 is released!

### ISSUE THREAD

**Issue by frol** [mijime/docker-mattermost#17]
https://www.mattermost.org/mattermost-3-3-chinese-korean-dutch-message-flags-here-golang-bot-sample-and-much-more/

**Comment by mijime** [comment]
Thanks!!!

**Comment by mijime** [comment]
I tried my best, but have a same error with `npm build`. 

This time, took advantage of what was pre-built only nodes.
Likely to work in there in the environment?

**Comment by mijime** [comment]
🙇

**Comment by frol** [comment]
> I tried my best, but have a same error with npm build.

Could you, please, post the build log?

**Comment by mijime** [comment]
Okay! 

``` Dockerfile
FROM alpine:3.4

ENV ENTRYKIT_VER=0.4.0 \
    MATTERMOST_VER=3.3.0 \
    GOPATH=/opt/go

RUN apk add --no-cache ca-certificates \
    && apk add --no-cache --virtual=.build-dependencies \
      go git mercurial nodejs make g++ curl libpng-dev libpng nasm autoconf automake \
    && curl -sSL https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VER}/entrykit_${ENTRYKIT_VER}_Linux_x86_64.tgz \
      | tar -xzC /usr/local/bin \
    && /usr/local/bin/entrykit --symlink \
    && go get github.com/tools/godep \
    && npm update npm --global \
    && git clone --depth 1 --branch v${MATTERMOST_VER} \
      https://github.com/mattermost/platform \
      ${GOPATH}/src/github.com/mattermost/platform \
    && cd ${GOPATH}/src/github.com/mattermost/platform \
    && sed -i.org 's/sudo //g' Makefile \
    && make package BUILD_NUMBER=${MATTERMOST_VER} \
    && cd - \
    && rm -rf \
      ${GOPATH} \
      /usr/lib/go/pkg \
      /usr/lib/node_modules \
      /root/.npm \
      /root/.node-gyp \
      /tmp/npm-* \
    && apk del --purge .build-dependencies \
    && addgroup mattermost -S \
    && adduser mattermost -S -G mattermost \
    && chown root:mattermost -R /opt/mattermost \
    && mkdir -p /etc/mattermost /var/log/mattermost /var/mattermost/data \
    && rm -r /opt/mattermost/logs /opt/mattermost/config \
    && ln -sf /etc/mattermost /opt/mattermost/config \
    && ln -sf /var/log/mattermost /opt/mattermost/logs \
    && ln -sf /var/mattermost/data /opt/mattermost/data \
    && chown root:mattermost -R /etc/mattermost \
    && chown mattermost: -R /var/mattermost/data /var/log/mattermost \
    && chmod o-rw -R /etc/mattermost /var/mattermost/data /var/log/mattermost

ADD assets/runtime /opt/mattermost/runtime
RUN chmod +x /opt/mattermost/runtime/entrypoint.sh

EXPOSE 80
VOLUME /etc/mattermost /var/log/mattermost /var/mattermost/data
WORKDIR /opt/mattermost

ENTRYPOINT [ \
  "/opt/mattermost/runtime/entrypoint.sh", \
  "switch", "sh=/bin/sh", "/bin/sh=/bin/sh", \
  "--", \
  "render", "/etc/mattermost/config.json", \
  "--", \
  "/opt/mattermost/bin/platform" ]
```

console error log...

```
ERROR in ./images/favicon/android-chrome-192x192.png
    Module build failed: Error: spawn /opt/go/src/github.com/mattermost/platform/webapp/node_modules/pngquant-bin/vendor/pngquant ENOENT
            at exports._errnoException (util.js:953:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
      at onErrorNT (internal/child_process.js:348:16)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
   @ ./~/html-webpack-plugin/lib/loader.js!./root.html 1:1755-1809

   npm ERR! Linux 4.4.17-boot2docker
   npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
   npm ERR! node v6.2.0
   npm ERR! npm  v3.10.7
   npm ERR! code ELIFECYCLE
   npm ERR! mattermost-webapp@0.0.1 build: `NODE_ENV=production webpack`
   npm ERR! Exit status 2
   npm ERR!
   npm ERR! Failed at the mattermost-webapp@0.0.1 build script 'NODE_ENV=production webpack'.
   npm ERR! Make sure you have the latest version of node.js and npm installed.
   npm ERR! If you do, this is most likely a problem with the mattermost-webapp package,
   npm ERR! not with npm itself.
   npm ERR! Tell the author that this fails on your system:
   npm ERR!     NODE_ENV=production webpack
   npm ERR! You can get information on how to open an issue for this project with:
   npm ERR!     npm bugs mattermost-webapp
   npm ERR! Or if that isn't available, you can get their info via:
   npm ERR!     npm owner ls mattermost-webapp
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
```

container log...

[docker-mattermost-log.txt](https://github.com/mijime/docker-mattermost/files/427000/docker-mattermost-log.txt)

**Comment by frol** [comment]
@mijime I have finally had some spare moments to look at the issue. You needed only to install `pngquanta` from Alpine repos and replace the npm vendored version of it (the following patch is based on Mattermost 3.2.0 Dockerfile with bumped version to 3.3.0):

``` patch
+    && apk add pngquant --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
+    && sed -i 's|npm install|& \&\& ln -sf /usr/bin/pngquant ./node_modules/pngquant-bin/vendor/pngquant|' webapp/Makefile \
     && make package BUILD_NUMBER=${MATTERMOST_VER} \
```

However, should we bother with building assets from sources?

**Comment by mijime** [comment]
Thanks!! It's so nice solution.

> However, should we bother with building assets from sources?

Yeah, I'm also the same idea. I think to better to use assets from official build.
